name: at_end2end_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.atsign.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_client:
    path: ../at_client

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: encode_public_data
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: at_persistence_encode_public_data
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: at_secondary_encode_public_data
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
